// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urtwmfqncuwopkvzdcxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVydHdtZnFuY3V3b3BrdnpkY3hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjI4OTEsImV4cCI6MjA2NTU5ODg5MX0.86DzUecU0zF5ZlbOaPWXBeTCJEwI2AFkxyigTi_v2iI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);